services:
  - type: web
    name: automobile-shop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DB_HOST
        value: localhost         
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: ""                
      - key: DB_NAME
        value: automobile_shop
